### PR TITLE
Reference mavsdk_server framework directly from mavlink/MAVSDK release

### PR DESCRIPTION
**Pull request by byuarus**
- I have removed reference to MAVSDK-XCFramework and used direct link to mavlink/MAVSDK release in a binary target "mavsdk_server". In this case we don't need to use MAVSDK-XCFramework repo.
- added RxBlocking dependency as our unit tests target was failing without it

I've tested it with XCode 12.5.1.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
@kylewludwig: do you have an opinion about that? I don't remember why we needed the MAVSDK-XCFramework repository back then, and I am somehow hoping that we don't need it anymore (maybe SPM fixed something, I don't know). Could it be? :blush:

**Comment by kylewludwig** [comment]
> @kylewludwig: do you have an opinion about that? I don't remember why we needed the MAVSDK-XCFramework repository back then, and I am somehow hoping that we don't need it anymore (maybe SPM fixed something, I don't know). Could it be? 😊

I believe we had to make a separate binary Swift Package to ensure the builds can be archived for App Store release. If we didn’t, builds would work locally but we’d fail to upload releases to the App Store.

I haven’t had a project recently that requires this so it could have changed since then. I would test this by going to Product > Archive in Xcode and see if/where the upload fails in the process (assuming you have App Store Connect setup for your Apple Developer ID.)

**Comment by julianoes** [comment]
@byuarus should we merge this BTW?

**Comment by byuarus** [comment]
@julianoes yes I think you can merge it. With the fix that @JonasVautherin has implemented for the mavsdk_server.xcframework.zip packaging on CI we can use direct link to the MAVSDK release. 
I have tested with XCode 13.0 and I had no issues with uploading our app to testflight and it pointed to the latest commit in this PR.

**Comment by julianoes** [comment]
Thanks @byuarus!

**Pull request merged**
