### PR TITLE
Cocoapods attempt

### PR DESCRIPTION
**Pull request by bluecamel**

### CODE REVIEW

**Comment by bluecamel** [comment]
This doesn't download the `mavsdk_server.framework` zip and unzip it, so that's something that I'm doing manually.  I'm downloading and unzipping it in the main directory.

**Comment by julianoes** [comment]
@bluecamel thanks for that.  What's missing would be documentation for the readme on how to use it.

**Comment by bluecamel** [comment]
> @bluecamel thanks for that. What's missing would be documentation for the readme on how to use it.

Hey @julianoes, it's currently incomplete.  I believe that it works in the `MAVSDK-Swift-Example` project because of specific config already in that project.  At the very least, it does not properly expose dependency frameworks to consuming libraries, which was a problem for me, as I was installing it in a pod that was a dependency of another project.  It may be that this works in the simple case, but I haven't been able to verify.

Anyhow, I plan to get back to it, but it may be a week or so.

**Comment by unipheas** [comment]
@bluecamel How is this coming? Do you need any help with it?

**Comment by JonasVautherin** [comment]
Let's close for now, as mentioned in the corresponding issue. @bluecamel feel free to reopen if you have news on that!

**Pull request closed without merging**
