### PR TITLE
update to backend service

### PR DESCRIPTION
**Pull request by unipheas**
When attempting to update the backend I ran into this error after running `bash tools/generate_from_protos.bash`

```
## Generating the SDK wrappers
Traceback (most recent call last):
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/bin/protoc-gen-dcsdk", line 11, in <module>
load_entry_point('protoc-gen-dcsdk', 'console_scripts', 'protoc-gen-dcsdk')()
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/**main**.py", line 17, in main
AutoGen.generate_reactive(request).SerializeToString())
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/autogen.py", line 67, in generate_reactive
f.content = str(out_file)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/autogen_file.py", line 31, in **repr**
has_result=self._has_result)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, _args, *_kwargs)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/Users/unipheas/Developer/MAVSDK-Swift/tools/../templates/file.j2", line 42, in top-level template code
{{ indent(struct, 1) }}
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/utils.py", line 78, in jinja_indent
_in_str = str(_in_str)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/struct.py", line 43, in **repr**
nested_structs=self._nested_structs)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, _args, *_kwargs)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/Users/unipheas/Developer/MAVSDK-Swift/tools/../templates/struct.j2", line 7, in top-level template code
{{ '\n' + indent(nested_enums[nested_enum], 1) }}
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/utils.py", line 78, in jinja_indent
_in_str = str(_in_str)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/protoc_gen_dcsdk/enum.py", line 30, in **repr**
parent_struct=self._parent_struct)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
return original_render(self, _args, *_kwargs)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "/Users/unipheas/Developer/MAVSDK-Swift/tools/../templates/enum.j2", line 4, in top-level template code
case {{ value.name.lower_camel_case }}
File "/Users/unipheas/Developer/MAVSDK-Swift/proto/pb_plugins/venv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'protoc_gen_dcsdk.name_parser.NameParser object' has no attribute 'name'
--custom_out: protoc-gen-custom: Plugin failed with status code 1.
```

Once this is fixed we can merge this in.

### CODE REVIEW

**Comment by unipheas** [comment]
Noticing that RXSwift is still on Swift 5.0.1. We may have to hold off until that is also updated. 
```
Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7).
```

**Comment by unipheas** [comment]
My bad, I thought that was the procedure to clear things out. Could this be the problem I’m having?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JonasVautherin** [comment]
Did you run `carthage update --platform iOS`? To me it gives the same error message (saying that the latest binary released by RxSwift was built with 5.0.1), but then it says "falling back to compiling from sources", and it just works.

**Comment by unipheas** [comment]
Right, I've done `carthage update --platform ios` and it also works. However, after I run `bash tools/generate_from_protos.bash` and that's where it is coming up with the error. Am I doing this incorrectly?

**Comment by JonasVautherin** [comment]
Closing in favor of #155

**Pull request closed without merging**
